entity-store/build.gradle
When a gradle install the maven artefacts in the repo get overridden.
=> XD-455: During the maven publish task the test jar does replace the main jar

build.gradle
Thanks for Xodus - I like it :)
I've updated the version of Kotlin to use the current build 1.2.21, this makes integration into projects easier (no libraries of different versions included).
Tests are passing here.
=> Update Kotlin to 1.2.21 and source version to 1.2

environment/src/main/kotlin/jetbrains/exodus/io/FileDataWriter.kt
Hello! I've faced with such problem. If you try to recreate environment several times you'll see file descriptors count increasing. According to  `lsof -p <pid>` I've found `dirChannel` hasn't been closing at all. So, I hope it'll help.
=> File descriptors leaking issue fix

entity-store/src/main/java/jetbrains/exodus/entitystore/PersistentEntityStoreImpl.java
Only log production relevant information on INFO level and so avoid cluttering log output.
I want to use xodus in an environment where I can not control the log configuration and therefore can not fine tune / change the log level of a 3rd party library.
=> Tune info level logging

openAPI/src/main/java/jetbrains/exodus/crypto/StreamCipherProvider.java, openAPI/src/main/java/jetbrains/exodus/io/DataReaderWriterProvider.java
This PR fixes the following exception in environments where `Thread.currentThread().getContextClassLoader()` is not the right `ClassLoader` for these services.
```
jetbrains.exodus.InvalidSettingException: Unknown DataReaderWriterProvider: jetbrains.exodus.io.FileDataReaderWriterProvider
at jetbrains.exodus.log.LogConfig.getReaderWriterProvider(LogConfig.java:302) ~[?:?]
at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:117) ~[?:?]
at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:105) ~[?:?]
at jetbrains.exodus.env.Environments.newInstance(Environments.java:60) ~[?:?]
at jetbrains.exodus.entitystore.PersistentEntityStores.newInstance(PersistentEntityStores.java:64) ~[?:?]
at jetbrains.exodus.entitystore.PersistentEntityStores.newInstance(PersistentE …
```
=> Check additional ClassLoader for services

entity-store/readme.md
This change adds information about the fact that read-only transaction can only be finished by using the abort() method.
=> Add hint how to finish a read-only transaction

entity-store/readme.md
In the `readme.md` the name of the function `StoreTransaction.findWithLinks` is wrongly stated as `StoreTransaction.findWithLinks`.
=> Correct the name of the method 'findWithLinks'

openAPI/src/main/java/jetbrains/exodus/entitystore/PersistentEntityStoreConfig.java
This change disables Management in PersistentEntityStoreConfig by default.
This is done the same way as in EnvironmentConfig.
This change relates to issue XD-655.
=> Disable management in Android; #XD-655

build.gradle
The URL for the license is incorrect (missing `s`) and should probably use https instead
=> Fixed typo in license URL

entity-store/src/main/java/jetbrains/exodus/entitystore/FileSystemBlobVault.java, entity-store/src/main/java/jetbrains/exodus/entitystore/FileSystemBlobVaultOld.java, entity-store/src/main/java/jetbrains/exodus/entitystore/PersistentEntityStoreImpl.java, entity-store/src/main/java/jetbrains/exodus/entitystore/PersistentStoreTransaction.java, entity-store/src/main/java/jetbrains/exodus/entitystore/VFSBlobVault.java, entity-store/src/main/kotlin/jetbrains/exodus/crypto/EncryptedBlobVault.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/DummyBlobVault.kt, environment/src/main/java/jetbrains/exodus/env/EnvironmentImpl.java, environment/src/main/java/jetbrains/exodus/env/TransactionBase.java, openAPI/src/main/java/jetbrains/exodus/entitystore/BlobVault.java, openAPI/src/main/java/jetbrains/exodus/entitystore/DiskBasedBlobVault.java, utils/src/main/java/jetbrains/exodus/util/UTFUtil.java
1. Callback which allows executing version post-validation actions before data flush was added.
2. BufferedInputStreams are used instead of ByteArray streams to fall back to the stored position during the processing of stream inside EntityStore. Which should decrease the risk of OOM.
3. All streams are stored in the temporary directory before transaction flush (after validation of the transaction version) and then moved to the BlobVault location after a successful commit. That is done gracefully handling situations when streams generate errors while storing the data.
4. Passed-in streams are automatically closed during commit/flush and abort/revert of transaction.
=> Issue XD-908 was fixed.

entity-store/src/main/java/jetbrains/exodus/entitystore/FileSystemBlobVaultOld.java, entity-store/src/main/java/jetbrains/exodus/entitystore/PersistentEntityStoreImpl.java, entity-store/src/main/java/jetbrains/exodus/entitystore/VFSBlobVault.java, entity-store/src/main/kotlin/jetbrains/exodus/crypto/EncryptedBlobVault.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/DummyBlobVault.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/EntityBlobTests.kt, openAPI/src/main/java/jetbrains/exodus/entitystore/BlobVault.java, openAPI/src/main/java/jetbrains/exodus/entitystore/DiskBasedBlobVault.java, openAPI/src/main/java/jetbrains/exodus/entitystore/PersistentEntityStoreConfig.java
When using the file system for storing blobs, the content is written after committing metadata in the Xodus Environment. That implies a delay between transaction acknowledgement and the actual writing of data which can cause a situation when blob content can be incorrectly read in another thread. Blob content is checked before returning to the user to avoid such situations. If the content is incomplete, the thread will wait a specified time in seconds until the transaction wholly writes blob content. Otherwise, an exception will be thrown.
(cherry-picked from commit 343b730839e50975c062185d47125bed6b73d0b8)
=> Issue #XD-904 fixed

entity-store/src/main/java/jetbrains/exodus/entitystore/PersistentEntity.java, entity-store/src/main/java/jetbrains/exodus/entitystore/PersistentEntityStoreImpl.java, openAPI/src/main/java/jetbrains/exodus/entitystore/Entity.java
1. New input buffer is created only if the passed in the input stream is not buffered.
2. Stream, which is stored in a transaction is returned as the result of the call of the #setBlob method.
=>  New input buffer is created only if passed in input stream is not buffered.

entity-store/src/main/java/jetbrains/exodus/entitystore/EmptyId.java, entity-store/src/main/java/jetbrains/exodus/entitystore/PersistentEntityId.java
Special not existing entityId is used as indication of end of data processing in EntityIterables.
=> Issue XD-910 was fixed

environment/src/main/java/jetbrains/exodus/env/EnvironmentImpl.java, environment/src/main/java/jetbrains/exodus/log/StartupMetadata.java, environment/src/main/kotlin/jetbrains/exodus/log/Log.kt
The database is read-only if its content is stored under the V1 version.
=> Metadata files are not created for the V1 binary format.

README.md
- Uses `implementation` instead of `compile` (the latter has been deprecated for a while now)
- Uses Kotlin-style syntax (with parentheses and double-quotes). This syntax is backwards-compatible with Groovy, so will still work for Groovy users. :)
=> Update dependency snippet in README

environment/src/main/java/jetbrains/exodus/env/EnvironmentImpl.java, environment/src/main/java/jetbrains/exodus/env/TransactionBase.java, environment/src/main/kotlin/jetbrains/exodus/env/StuckTransactionMonitor.kt, environment/src/main/kotlin/jetbrains/exodus/env/management/BackupController.kt
Internal transaction of backupController is no more monitored by stuck transaction monitor and not cancelled after a timeout.
Add check in stuck transaction monitor and add property to BaseTransaction.
Described transaction can be cancelled by StuckTransaction monitor and this will cause state that cannot be fixed in runtime.
=> Add unmonitored transactions

vectoriadb-java-client/src/main/java/jetbrains/vectoriadb/client/VectoriaDBClient.java, vectoriadb-server/src/main/java/jetbrains/vectoriadb/server/IndexManagerServiceImpl.java, vectoriadb-server/src/test/java/jetbrains/vectoriadb/server/IndexManagerTest.java
A couple of fixes for VectoriaDB server
Every commit corresponds to a fix. Please review on the commit-by-commit basis.
=> VectoriaDB server fixes

environment/src/main/kotlin/jetbrains/exodus/env/management/BackupController.kt, environment/src/main/kotlin/jetbrains/exodus/env/management/BackupControllerMBean.kt
We can access if backup is finished or not to prevent auto unload
A biiig problem with backups caused lots of servers to go to unavailable
=> Added information about backup controller marker transaction state

environment/src/main/java/jetbrains/exodus/tree/patricia/PatriciaTraverser.java, openAPI/src/main/java/jetbrains/exodus/ByteIterableBase.java
* Pre-allocate bytearray of the corresponding size to avoid excessive garbage
* Short-circuit the most common path on fillBytes
It significantly speeds up the traversal on the following benchmark and, depending on the workload, is visible in hot profiles, both locally and in production:
```
@Threads(8) // Tune it 
@Warmup(iterations = 5, time = 1)
@Measurement(iterations = 5, time = 1)
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.MILLISECONDS)
@State(Scope.Benchmark)
@Fork(2)
open class EntityIteratorBaseSharedCache {
companion object {
val instance: PersistentEntityStoreImpl
init {
val tmp = kotlin.io.path.createTempDirectory("EntityIteratorBaseSharedCache").toFile()
instance = PersistentEntityStores.newInstance(tmp);
val txn = instance.beginTransaction()
for (i in …
```
=> Optimize PatriciaTraverser routine

benchmarks/src/jmh/java/jetbrains/exodus/benchmark/env/JMHBitmapIteratorBenchmark.java, environment/src/main/kotlin/jetbrains/exodus/env/BitmapIterator.kt
The BitmapIterator purpose is to iterate over an indexed bit-set stored via Cursor, that is usually stored on a disk.
Use of nullable Long values for next/current values causes JVM to perform boxing/unboxing operations on the values causing unnecessary allocations.
See https://docs.oracle.com/javase/8/docs/technotes/guides/language/autoboxing.html
Difference in the benchmark:
```
Benchmark                                    Mode  Cnt     Score    Error  Units
Before: JMHBitmapIteratorBenchmark.iterate  thrpt    5  1454,327 ± 20,185  ops/s
After:  JMHBitmapIteratorBenchmark.iterate  thrpt    5  1542,706 ± 33,814  ops/s
```
=> Optimize BitmapIterator by removing Long boxing

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/ODatabaseProvider.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OPersistentEntityStore.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OSchemaBuddy.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionImpl.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OVertexEntity.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OPersistentStoreTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OSchemaBuddyTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/testutil/InMemoryOrientDB.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/testutil/OrientDBIssues.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/OModelMetaData.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/OrientDbSchemaInitializer.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/MigrateDataTest.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/MigrateXodusToOrientDbSmokeTest.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/OModelMetaDataTest.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/OrientDbSchemaInitializerTest.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/SchemaTestUtils.kt
Here I wrapped up all the "main players" (ODataMigrator, OPersistentEntityStore, OModelMetadata) and made them work together.
Interesting stuff:
1. OPersistentEntityStore now has OSchemaBuddy to delegate the schema-related operations. There is OSchemaBuddyImpl on the entity-store package to make it self-sufficient. OPersistentTransaction.newEntity(...) still does not work if the schema has not been created in advance because OrientDB does not support schema changes in transactions. But when OrientDB supports schema changes in transactions, OPersistentTransaction.newEntity(...) will work without pre-created schema.
2. OModelMetadata implements OSchemaBuddy, so it can be passed to OPersistentEntityStore to delegate schema-related operations. So, OModelMetadata will handle all the …
=> Make ODataMigrator, OEntityStore and OModelMetadata work together

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OVertexEntity.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/MigrateDataTest.kt
As we cannot distinguish string-blobs from blobs on migration level we need to store binary content in orientDB. Also we need to 
use UTFUtil from xodus, to ensure compatibility.
=> #XD-1048 fixed

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OSchemaBuddy.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/testutil/InMemoryOrientDB.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/OrientDbSchemaInitializerTest.kt
Schema init failed because it used to require ClassID from StringBlob and Blob that were created as vertex classes. No they are in ignored set along with vertex class itself
=> #XD-1049 fixed

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OCondition.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OConditions.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OQueryFunctions.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/OEntityIterableBaseTest.kt
[XD-1000](https://youtrack.jetbrains.com/issue/XD-1000) [Query] Express difference as AND NOT wherever possible
Example of resulting SQL:
"Query: SELECT FROM Issue WHERE (complex = ? AND NOT (blocked = ?)), params: [true, true]"
=> XD-1000: Express difference as AND NOT wherever possible

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/ODatabaseProvider.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OPersistentEntityStore.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransaction.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionImpl.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/testutil/InMemoryOrientDB.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/CountingOTransaction.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/XodusToOrientDataMigrator.kt, query/src/test/kotlin/jetbrains/exodus/query/OQueryEngineTest.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/MigrateDataTest.kt
Two fixes are here:
1. A fix for the deduplication logic (for the data migrator)
2. A fix for handling OTransactions. Please, review it carefully. I added there a test that illustrates the problem with the previous approach (also read the commit comments). With the previous approach the test fails after the flush(). Now the test works.
=> A couple of fixes here and there

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/OQueryEntityIterableBase.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OCondition.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OLimit.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OOrder.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OQuery.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OQueryExecution.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OQueryFunctions.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OQueryTimeout.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OSelect.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OSkip.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OSql.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/query/OQueryTest.kt
Fix `kotlinx.dnq.query.IsInQueryTest` test by introducing unique LET argument names with depth using SqlBuilder instead of StringBuilder.
https://youtrack.jetbrains.com/issue/XD-1065/Fix-XDNQ-tests-related-to-query-generation
=> XD-1065: Add depth for sql query building

query/build.gradle.kts, query/src/main/kotlin/jetbrains/exodus/query/metadata/CountingOTransaction.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/MigrateXodusToOrient.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/XodusToOrientDataMigrator.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/XodusToOrientDataMigratorLauncher.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/MigrateYourDatabaseTest.kt
A couple of UX improvements for the data migrator:
1. Now it is possible to pass `entityPerTransaction` param via the command line
2. Now we count comited transactions during the data migration
=> Minor UX improvements for data migrator

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OVertexEntity.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/IndicesCreator.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/OrientDbSchemaInitializer.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/OrientDbSchemaInitializerTest.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/SchemaTestUtils.kt
The links duplication problem is solved now in the following way: 
1. On adding a link, we check if there is already the same link. If there is, we just silently skip new one, if there is no, we add the new one. 
2. We do this checking only if there is an appropriate index for the edge class (for the in and out edges). If there is no an index, we do not check for link duplicates.
Check out the new tests to see how it works.
=> Make links unique with the help of indices

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionImpl.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OVertexEntity.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/testutil/OrientDBIssues.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/OModelMetaDataTest.kt
This behaviour is needed to ensure that we can "load" deleted entities for DNQ.
=> During the load entity is created in detached form and real record loaded only on the first request.

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OVertexEntity.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OEntityTest.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/OrientDbSchemaInitializerLinkIndicesTest.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/SchemaTestUtils.kt
Fixed OVertexEntity.deleteLink() and Co, OVertexEntity.setLink() and Co. Added tests.
=> Delete links with indices

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OCondition.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OQuery.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OQueryExecution.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OQueryFunctions.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OSelect.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OSql.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/query/OQueryTest.kt
Turned out that for some cases just "?" param substitution and enumarable list does not work. Didn't plunge in the details, just fixed as anyway wanted to use named params.
=> XD-1065: Use named query parameters

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/ODatabaseProviderImpl.kt
Add some config parameters to underlying orientDB
=> Tweak DB config from users-scoped application

query/src/main/kotlin/jetbrains/exodus/query/QueryEngine.kt, query/src/main/kotlin/jetbrains/exodus/query/SortEngine.kt
=> Replace link to EIB.EMPTY to OEIB.EMPTY

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/ODatabaseProvider.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/ODatabaseProviderImpl.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionImpl.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/OEntityIterableBase.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/link/OVertexEntityIterable.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/ODatabaseProviderTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionLifecycleTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OTransactionLifecycleTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/testutil/OTestMixin.kt, openAPI/src/main/java/jetbrains/exodus/entitystore/EntityIterable.java, query/src/main/kotlin/jetbrains/exodus/query/InMemoryEntityIterable.kt
1. Supported the database-wise read-only mode. 
* If there are active write transactions at the moment when the read-only mode gets enabled, those transactions will fail on commit.
3. Moved findLinks(...) method to EntityIterable. So, it is declared and available on the interface level.
=> Some fixes here and there

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OPersistentEntityStore.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OSchemaBuddy.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransaction.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionImpl.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OVertexEntity.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/ODatabaseProviderTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OEntityTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OPersistentStoreTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OSchemaBuddyTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OTransactionLifecycleTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/testutil/InMemoryOrientDB.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/testutil/OTestMixin.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/CountingTransaction.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/IndicesCreator.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/OModelMetaData.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/OrientDbSchemaInitializer.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/OModelMetaDataTest.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/OrientDbSchemaInitializerTest.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/SchemaTestUtils.kt
1. Supported adding new link types in a transaction. For such links, we create only the edge class and the unique index. We do not add "in and out" properties to the vertex classes, because it does not bring any value (we do not have any cardinality restrictions for ad-hoc links), and it may cause concurrency errors (see the tests for details).
2. A couple of fixes here and there.
=> Support adding new links in a transaction

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionImpl.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OPersistentStoreTest.kt
Restored contract for txn.toEntityId method
=> #XD-1169 fixed

query/src/main/kotlin/jetbrains/exodus/query/SortEngine.kt
It did casts to OEntityIterableBase to call unwrap() where EntityIterable was enough
=> Dropped unnecessary ClassCast

entity-store/build.gradle.kts, query/src/test/kotlin/jetbrains/exodus/query/OBinaryOperationsWithSortTest.kt
Libraries updated. Tests unignored
=> Graph store xd 1116

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBPersistentEntityStore.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/youtrackdb/OPersistentStoreTest.kt, openAPI/src/main/java/jetbrains/exodus/entitystore/PersistentEntityStore.java, persistent-entity-store/src/main/java/jetbrains/exodus/entitystore/PersistentEntityStoreImpl.java
propagate getter for read-only flag to the the store
The solution (cloud) is designed to use only `PersistentEntityStore` as the entry point for database access. It is necessary to assess whether the given store is in read-only mode.
https://youtrack.jetbrains.com/issue/XD-1195/
[x] I have added unit tests to the code I am submitting
[x] My unit tests cover both failure and success scenarios
=> XD-1195 propagated read-only mode flag to the store

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBSchemaBuddy.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBStoreTransactionImpl.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBVertexEntity.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/iterate/YTDBQueryEntityIterator.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/query/YTDBQueryFunctions.kt
Closing YTDB result sets after usage. This can make sense during big transactions that perform dozens of queries.
=> Closing YTDB result sets after querying

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/iterate/YTDBQueryEntityIterator.kt
YTDBQueryEntityIterator always has a ResultSet associated with it which needs to be disposed after usage.
=> YTDBQueryEntityIterator.shouldDispose=true

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/iterate/YTDBEntityIterableBase.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/query/YTDBQueryFunctions.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/query/YTDBSelect.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/query/YTDBSql.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/youtrackdb/iterate/YTDBEntityIterableTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/youtrackdb/query/YTDBQueryTest.kt
Optimizing some COUNT query generation for better performance:
`SELECT COUNT(*) FROM (SELECT FROM A)` -> `SELECT COUNT(*) FROM A`
`SELECT COUNT(*) FROM (SELECT expand(in(linkName)) FROM A)` -> `SELECT in(linkName).size() FROM A`
`SELECT COUNT(*) FROM (SELECT expand(out(linkName)) FROM A)` -> `SELECT out(linkName).size() FROM A`
=> COUNT sql query optimization
