JetBrains/xodus

benchmarks/build.gradle, benchmarks/src/jmh/java/jetbrains/exodus/benchmark/TokyoCabinetBenchmark.java, benchmarks/src/jmh/java/jetbrains/exodus/benchmark/chronicle/JMHChronicleMapTokyoCabinetBenchmarkBase.java, benchmarks/src/jmh/java/jetbrains/exodus/benchmark/env/JMHEnvTokyoCabinetBenchmarkBase.java, benchmarks/src/jmh/java/jetbrains/exodus/benchmark/h2/JMH_MVStoreTokyoCabinetBenchmarkBase.java, benchmarks/src/jmh/java/jetbrains/exodus/benchmark/lmdb/JMH_LMDBTokyoCabinetBenchmarkBase.java, benchmarks/src/jmh/java/jetbrains/exodus/benchmark/lmdb/JMH_LMDBTokyoCabinetReadBenchmark.java, benchmarks/src/jmh/java/jetbrains/exodus/benchmark/lmdb/JMH_LMDBTokyoCabinetWriteBenchmark.java, benchmarks/src/jmh/java/jetbrains/exodus/benchmark/mapdb/JMHMapDbTokyoCabinetBenchmarkBase.java
LMDB is probably the most popular analog of Berkley DB, and have many similarities with Xodus:
http://www.lmdb.tech/doc/
=> XD-579 Benchmark of LMDB similar to Tokyo Cabinet benchmark

benchmarks/build.gradle, benchmarks/src/jmh/java/jetbrains/exodus/benchmark/persistit/JMHPersistItTokyoCabinetBenchmarkBase.java, benchmarks/src/jmh/java/jetbrains/exodus/benchmark/persistit/JMHPersistItTokyoCabinetReadBenchmark.java, benchmarks/src/jmh/java/jetbrains/exodus/benchmark/persistit/JMHPersistItTokyoCabinetWriteBenchmark.java
Just for fun, I have added Akiban PersistIt to the benchmarks.
=> Add Akiban PersistIt to the benchmarks

environment/src/main/java/jetbrains/exodus/env/EnvironmentImpl.java, environment/src/main/java/jetbrains/exodus/env/TransactionSet.java
Fixes https://xodus.myjetbrains.com/youtrack/issue/XD-625
=> Fix oldest root address #XD-625

README.md
to make the example code compilable
=> add missing semicolon

build.gradle
=> Fix publication for 1.3 version

build.gradle
Fixed publication for version 2.0
=> Fix publication for 2.0 version

build.gradle
Fixed publication for version 3.0
=> Fix publication for 3.0 version

entity-store/src/main/java/jetbrains/exodus/entitystore/FileSystemBlobVault.java, entity-store/src/main/java/jetbrains/exodus/entitystore/FileSystemBlobVaultOld.java, entity-store/src/main/java/jetbrains/exodus/entitystore/PersistentEntityStoreImpl.java, entity-store/src/main/java/jetbrains/exodus/entitystore/PersistentStoreTransaction.java, entity-store/src/main/java/jetbrains/exodus/entitystore/TmpBlobVaultFileInputStream.java, entity-store/src/main/java/jetbrains/exodus/entitystore/VFSBlobVault.java, entity-store/src/main/kotlin/jetbrains/exodus/crypto/EncryptedBlobVault.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/DummyBlobVault.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/BlobVaultTests.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/EntityBlobTests.kt, openAPI/src/main/java/jetbrains/exodus/entitystore/BlobVault.java, openAPI/src/main/java/jetbrains/exodus/entitystore/DiskBasedBlobVault.java, openAPI/src/main/java/jetbrains/exodus/entitystore/Entity.java, openAPI/src/main/java/jetbrains/exodus/entitystore/PersistentEntityStoreConfig.java, utils/src/main/java/jetbrains/exodus/core/dataStructures/Pair.java
Storing of the stream data was moved from commit to the call of Entity#setBlob method.
=> Performance of blobs handling was improved.

entity-store/src/main/java/jetbrains/exodus/entitystore/PersistentEntityStoreBackupStrategy.java
Fix the problem when valid blobs can be removed during backup.
=> Issue XD-909 has been fixed.

environment/src/main/java/jetbrains/exodus/log/BufferedDataWriter.java, environment/src/main/kotlin/jetbrains/exodus/log/Log.kt
Pages are moved at the end of the write into write and disk caches.
=> Committed high address should be set after syncing of pages.

crypto/src/main/kotlin/jetbrains/exodus/crypto/convert/ArchiveBackupableFactory.kt
=> Filtered metadata files from encryption

tools/src/main/kotlin/jetbrains/exodus/crypto/Scytale.kt
Migrated xodus-tools:scytale to BackupUtil
Use same tool for work with archives for 3.0, so it can support both 1.3 and 3.0 formats
=> Xodus tools scytale migration

entity-store/src/main/java/jetbrains/exodus/entitystore/EntityStoreSharedAsyncProcessor.java
Ability to update thread entitytStoreAsyncProcessor thread context
In fact we need an ability to route logs of multi-tier application
=> Tweaks for entity shared async processor

entity-store/src/main/java/jetbrains/exodus/entitystore/util/BackupUtil.java
Fixes wrong sized entry check
To make backup util work:)
=> Correct check for fixing wrong entry size in manual backup

crypto/src/main/kotlin/jetbrains/exodus/crypto/convert/ArchiveBackupableFactory.kt, entity-store/src/main/java/jetbrains/exodus/entitystore/PersistentEntityStoreBackupStrategy.java, entity-store/src/main/java/jetbrains/exodus/entitystore/PersistentEntityStoreImpl.java, entity-store/src/main/java/jetbrains/exodus/entitystore/util/BackupUtil.java, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/PersistentEntityStoreRefactorings.kt, environment/src/main/java/jetbrains/exodus/env/EnvironmentBackupStrategyImpl.java, environment/src/main/java/jetbrains/exodus/env/EnvironmentImpl.java, environment/src/main/java/jetbrains/exodus/log/BackupMetadata.java, environment/src/main/java/jetbrains/exodus/log/LogUtil.java, environment/src/main/java/jetbrains/exodus/log/StartupMetadata.java, environment/src/main/kotlin/jetbrains/exodus/env/Environments.kt, environment/src/main/kotlin/jetbrains/exodus/log/Log.kt, openAPI/src/main/java/jetbrains/exodus/env/EnvironmentConfig.java
Every time the database is restored from backup - a check of data structures is performed.
=> Tree structures check 3.0

entity-store/src/main/java/jetbrains/exodus/entitystore/PersistentEntityStoreImpl.java, entity-store/src/main/java/jetbrains/exodus/entitystore/PersistentSequentialDictionary.java, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/EntityTests.kt
When for some reason database has duplicated entityTypes it's better to be able to remove by id as they are different.
Database cleanup:)
=> Feature remove entity type by id

query/src/main/java/jetbrains/exodus/query/metadata/SimplePropertyMetaDataImpl.java
It is the first step to deliver Set<...> properties to OrientDB.
=> add type parameter names to SimplePropertyMetaDataImpl

query/src/main/java/jetbrains/exodus/query/metadata/SimplePropertyMetaDataImpl.java
It is a "cherry-pick" from the master.
=> Support type parameters in simple property

entity-store/src/test/kotlin/jetbrains/exodus/entitystore/BackupTests.kt
=> ignore failing test

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OReadonlyVertexEntity.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OVertexEntity.kt
=> Added OReadonlyEntity

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionImpl.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionTest.kt
Fix implementation for isReadOnly 
Failing test in xodus dnq
=> #XD-1046 fixed

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionImpl.kt
Adopt revert a and abort functions from oreintDB
=> Adopt orientDB revert and abort functions

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OVertexEntity.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/link/OLinkExistsEntityIterable.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/link/OLinkIterableToEntityIterable.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/link/OLinkIterableToEntityIterableFiltered.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/link/OLinkSelectEntityIterable.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/link/OLinkSortEntityIterable.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/link/OLinkToEntityIterable.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OEntityTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OEntityTests.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/testutil/OrientDBIssues.kt, query/src/main/java/jetbrains/exodus/query/LinkNotNull.java, query/src/main/kotlin/jetbrains/exodus/query/metadata/OrientDbSchemaInitializer.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/XodusToOrientDataMigrator.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/MigrateXodusToOrientDbSmokeTest.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/SchemaTestUtils.kt
this will allow us to use project.issue link (becuase it used to use 'issue' as edge name)
=> Add $link to all edge classes to avoid clashes with vertexes names

query/src/main/kotlin/jetbrains/exodus/query/metadata/OrientDbSchemaInitializer.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/OrientDbSchemaInitializerTest.kt
Do not see any reason to store it as date, as xodus-dnq operated them as longs
=> Store date-time property as long in orientdb

entity-store/src/main/java/jetbrains/exodus/entitystore/iterate/EntityIterableBase.java, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OComparableSet.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OQueryEntityIterable.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OVertexEntity.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/OQueryEntityIterableBase.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/link/OVertexEntityIterable.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OSelect.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionTest.kt, openAPI/src/main/java/jetbrains/exodus/entitystore/EntityIterable.java, query/src/main/java/jetbrains/exodus/query/LinkEqual.java, query/src/main/kotlin/jetbrains/exodus/query/SortEngine.kt, query/src/test/kotlin/jetbrains/exodus/query/OQueryEngineTest.kt
Moved not null check from xodus-dnq query generation to here.
=> Not null in select link from

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OPersistentEntityStore.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionImpl.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OVertexEntity.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/property/OPropertyEqualIterable.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/property/OSequenceImpl.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OPersistentStoreTest.kt, query/src/main/java/jetbrains/exodus/query/GetLinks.java, query/src/main/java/jetbrains/exodus/query/PropertyEqual.java
Sequences now are accessed, incremented, created in separate transactions.
It was required to support contract for xodus-dnq.
=> Reworked sequences

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/property/OInstanceOfIterable.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OCondition.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/OEntityIterableBaseTest.kt, query/src/main/java/jetbrains/exodus/query/InstanceOf.java
OrientDB has naitive instanceOf filtering. 
=> Added instanceof iterable

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/OQueryEntityIterableBase.kt
Intersects queryBasedIterable with single element iterable
=> Implemented contains for QueryBasedIerable

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OSchemaBuddy.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionTest.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/OrientDbSchemaInitializerTest.kt
Backward compatibility with how xodus worked on empty database
=> Graph store class sequence start from zero

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/OQueryEntityIterableBase.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/binop/OConcatEntityIterable.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OSelect.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionTest.kt
added toSet() in union query + added implementation to isEmpty()
=> Graph store unique union

query/src/main/kotlin/jetbrains/exodus/query/metadata/IndicesCreator.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/OrientDbSchemaInitializer.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/SchemaTestUtils.kt
=> Restriction on indexing of links is removed as not needed.

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionImpl.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/link/OLinkOfTypeToEntityIterable.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OSelect.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionTest.kt
findLinks returned linked entities of all types, not only of requested.
=> findLinks now take into account requested EntityType

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/link/OLinkIsNullEntityIterable.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/property/OPropertyIsNullIterable.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OCondition.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OConditions.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/OEntityIterableBaseTest.kt, query/src/main/java/jetbrains/exodus/query/LinkEqual.java, query/src/main/java/jetbrains/exodus/query/PropertyEqual.java, query/src/main/java/jetbrains/exodus/query/PropertyNotNull.java, query/src/main/java/jetbrains/exodus/query/UnaryNot.java, query/src/test/kotlin/jetbrains/exodus/query/OQueryEngineTest.kt
- Fix UnaryNot; 
- Add Property/Edge is null; 
- Fix difference optimisation
=> XD-1065: Fix UnaryNot; Property/Edge is null; difference optimisation

query/src/main/kotlin/jetbrains/exodus/query/SortEngine.kt
Unwrap source sorting elements
=> Update unwrap in sort

query/src/main/kotlin/jetbrains/exodus/query/metadata/OrientDbSchemaInitializer.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/OrientDbSchemaInitializerTest.kt
=> Fix blob types in schema

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OQueryFunctions.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OSelect.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/testutil/OUsersWithInheritanceTestCase.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/testutil/OrientDBUsers.kt, query/src/test/kotlin/jetbrains/exodus/query/OBinaryOperationsWithSortTest.kt
This tries to add sorting to queries with binary operations
=> Graph store binary operations sort

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OVertexEntity.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/link/OLinksFromEntityIterable.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/link/OVertexEntityIterable.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OSelect.kt
XdEntity.link.filter() didn't work
=> oVertexEntity.getLinks("linkName").intersect() now works

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/ORIDEntityId.kt
=> ID and hashcode updated to be compatible with x-dnq logic

query/src/main/kotlin/jetbrains/exodus/query/metadata/OrientDbSchemaInitializer.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/OrientDbSchemaInitializerTest.kt
In applications in many places not initialized boolean was treated like false so lot's of places will require db refactoerings.
=> Default false value for boolean fields

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OCondition.kt
=> Lowercase text search

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OVertexEntity.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OEntityTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OPersistentStoreTest.kt
=> #XD-1123 fixed

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OEntity.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OVertexEntity.kt
=> Added isLoaded to oVertexEntity

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OVertexEntity.kt
=> Fixed is loaded.

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/link/OVertexEntityIterable.kt
=> Unwrap OVertexEntityIterable. It's required for oVertexEntity.getLinks()

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OPersistentEntityStore.kt
OPerEnStore do not close databaseProvider anymore
=> OPersistent store do not close ODatabaseProvider anymore

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OPersistentEntityStore.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OSchemaBuddy.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransaction.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionImpl.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/query/OQueryExecution.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/OSchemaBuddyTest.kt
Also added explicit closing for oResultSet on transaction finishing
=> #XD-1142 fixed

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/OStoreTransactionImpl.kt
=> fix: Clean up println

query/src/main/kotlin/jetbrains/exodus/query/metadata/OrientDbSchemaInitializer.kt
=> XD-1165 removed unconditional modification in schema.

entity-store/build.gradle.kts, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/ODatabaseCompacter.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/ODatabaseConfig.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/ODatabaseProvider.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/ODatabaseProviderImpl.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/WrongUsernameTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/EncryptedDBTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/testutil/InMemoryOrientDB.kt, query/build.gradle.kts, query/src/main/kotlin/jetbrains/exodus/query/metadata/XodusToOrientDataMigratorLauncher.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/MigrateXodusToOrientDbSmokeTest.kt
Added encryption to ODatabaseProvider. Switched to OSystemDatabase user in terms of storing DB login and password
=> Graph store add encryption

entity-store/src/test/kotlin/jetbrains/exodus/entitystore/orientdb/EncryptedDBTest.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/MigrateXodusToOrient.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/XodusToOrientDataMigratorLauncher.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/MigrateYourDatabaseTest.kt
=> Updated DB migration code

query/build.gradle.kts, query/src/main/kotlin/jetbrains/exodus/query/metadata/XodusToOrientDataMigratorLauncher.kt, settings.gradle.kts
Flat to remove old database files after the migration
=> #XD-1178 fixed

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/orientdb/iterate/link/OMultipleEntitiesIterable.kt
=> Fixed contains in multple entitites iterable

query/src/main/kotlin/jetbrains/exodus/query/metadata/XodusToOrientDataMigratorLauncher.kt
Disables GC in xodus env created during migration
=> XD-1191 disable GC during data migration

query/src/main/kotlin/jetbrains/exodus/query/metadata/XodusToOrientDataMigratorLauncher.kt
updated patterns for (re)move old database
=> XD-1180 updated patterns for (re)move old database

build.gradle.kts, environment/src/main/kotlin/jetbrains/exodus/env/StuckTransactionMonitor.kt, environment/src/main/kotlin/jetbrains/exodus/gc/BackgroundCleaner.kt, lucene-directory-v2/build.gradle.kts, lucene-directory-v2/src/main/java/jetbrains/exodus/lucene2/XodusDirectory.java, lucene-directory-v2/src/main/kotlin/jetbrains/exodus/lucene2/codecs/Lucene101CodecWithNoFieldCompression.kt, lucene-directory-v2/src/main/kotlin/jetbrains/exodus/lucene2/codecs/Lucene87CodecWithNoFieldCompression.kt, lucene-directory-v2/src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec, lucene-directory-v2/src/test/java/jetbrains/exodus/lucene2/XodusDirectoryEncryptedTest.java, lucene-directory-v2/src/test/java/jetbrains/exodus/lucene2/XodusDirectoryNotEncryptedTest.java, lucene-directory-v2/src/test/kotlin/jetbrains/exodus/lucene2/XodusLuceneTests.kt, lucene-directory-v2/src/test/kotlin/jetbrains/exodus/lucene2/XodusLuceneTestsBase.kt, settings.gradle.kts
=> Release 3.1 lucene 10

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/iterate/YTDBEntityIterableBase.kt, query/src/test/kotlin/jetbrains/exodus/query/OperationsWithEmptyIterableTest.kt
Fix bug in operations with EMPTY
=> Fixed empty iterable operations

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBDatabaseProvider.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBDatabaseProviderImpl.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/youtrackdb/EncryptedDBTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/youtrackdb/WrongUsernameTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/youtrackdb/testutil/InMemoryYouTrackDB.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/MigrateXodusToOrient.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/MigrateXodusToOrientDbSmokeTest.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/MigrateYourDatabaseTest.kt
=> YTDB-248 Removed OSystem folder

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBPersistentEntityStore.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBStatistics.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBStatisticsImpl.kt
=> added simple stats interface to persistentStore

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBDatabaseProvider.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBDatabaseProviderImpl.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBPersistentEntityStore.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBStatisticsImpl.kt
Little updates required for migration
=> Added isOpen to store and updated some interfaces

query/src/main/kotlin/jetbrains/exodus/query/InMemoryEntityIterable.kt
Abstract layer is required for text search in YT
=> Extracted abstract in memory iterable

entity-store/build.gradle.kts
YouTrackDB version with the new metrics collection mechanism. (See https://github.com/youtrackdb/youtrackdb/pull/403)
=> YouTrackDB version with new metrics mechanism

entity-store/build.gradle.kts
YoutrackDB upgraded to youtrackdb-core:1.0.0-20250226.111557-19
=> youtrackdb-core:1.0.0-20250226.111557-19

entity-store/build.gradle.kts
YoutrackDB core version 1.0.0-20250226.144437-20 with fixed metric name
=> youtrackdb-core:1.0.0-20250226.144437-20

lucene-directory-v2/build.gradle.kts, lucene-directory-v2/src/main/java/jetbrains/exodus/lucene2/XodusDirectory.java, lucene-directory-v2/src/main/kotlin/jetbrains/exodus/lucene2/codecs/Lucene101CodecWithNoFieldCompression.kt, lucene-directory-v2/src/main/kotlin/jetbrains/exodus/lucene2/codecs/Lucene87CodecWithNoFieldCompression.kt, lucene-directory-v2/src/main/resources/META-INF/services/org.apache.lucene.codecs.Codec, lucene-directory-v2/src/test/java/jetbrains/exodus/lucene2/XodusDirectoryEncryptedTest.java, lucene-directory-v2/src/test/java/jetbrains/exodus/lucene2/XodusDirectoryNotEncryptedTest.java, lucene-directory-v2/src/test/kotlin/jetbrains/exodus/lucene2/XodusLuceneTests.kt, lucene-directory-v2/src/test/kotlin/jetbrains/exodus/lucene2/XodusLuceneTestsBase.kt, settings.gradle.kts
Cherry-picked commits to update lucene version
=> Graph store update lucene

entity-store/build.gradle.kts, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBDatabaseCompacter.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBStoreTransactionImpl.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/youtrackdb/OTransactionLifecycleTest.kt
Youtrackdb version upgrade: youtrackdb-core-1.0.0-20250516.124054-36
=> youtrackdb version upgrade

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/iterate/YTDBEntityIterableBase.kt
Closing YTDB iterators after usage
=> Closing YTDB result sets after querying (pt.2)

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/iterate/YTDBQueryEntityIterator.kt
Once YTDBQueryEntityIterator#hasNext returns false, we close it right away. This should fix some of the resource leaks that we have at the moment
=> closing YTDBQueryEntityIterator once hasNext returns false

entity-store/build.gradle.kts, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBDatabaseFactory.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBDatabaseParams.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBServerTest.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/SchemaTestUtils.kt
making serverConnectUser optional, as it might not be needed at all
=> YTDB server - making serverConnectUser optional

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBVertexEntity.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBEntityTest.kt
Fixes getLinkNames for YTDBEntity 
Not working entity bro
=> #XD-1205 fixed

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBDatabaseCompacter.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBDatabaseFactory.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBDatabaseParams.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBDatabaseProvider.kt, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBDatabaseProviderImpl.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/youtrackdb/EncryptedDBTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/youtrackdb/WrongUsernameTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBDatabaseProviderAdditionalUsersTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBDatabaseProviderTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBServerTest.kt, entity-store/src/test/kotlin/jetbrains/exodus/entitystore/youtrackdb/testutil/InMemoryYouTrackDB.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/MigrateXodusToOrient.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/MigrateXodusToOrientDbSmokeTest.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/MigrateYourDatabaseTest.kt
Logic for initialization additional YouTrackDB users on `YTDBDatabaseProvider` start.
=> Support for additional YTDB users

entity-store/build.gradle.kts
excluding transitive slf4j-jdk14
=> excluding transitive slf4j-jdk14

build.gradle.kts, entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBVertexEntity.kt
=> XD-1211 was fixed.

entity-store/src/main/kotlin/jetbrains/exodus/entitystore/youtrackdb/YTDBVertexEntity.kt, query/src/main/kotlin/jetbrains/exodus/query/metadata/DataAfterMigrationChecker.kt, query/src/test/kotlin/jetbrains/exodus/query/metadata/MigrateDataTest.kt
Added a test for migration of both string and stringblob property with same name
=> Updated getPropertyNames in migration to filter against YTDB entity
